/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppProviderRouteImport } from './routes/_authenticated/app.provider'
import { Route as AuthenticatedAppEmployerRouteImport } from './routes/_authenticated/app.employer'
import { Route as AuthenticatedAppEmployeeRouteImport } from './routes/_authenticated/app.employee'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppProviderRoute =
  AuthenticatedAppProviderRouteImport.update({
    id: '/provider',
    path: '/provider',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployerRoute =
  AuthenticatedAppEmployerRouteImport.update({
    id: '/employer',
    path: '/employer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployeeRoute =
  AuthenticatedAppEmployeeRouteImport.update({
    id: '/employee',
    path: '/employee',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/join': typeof AuthenticatedJoinRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/employee': typeof AuthenticatedAppEmployeeRoute
  '/app/employer': typeof AuthenticatedAppEmployerRoute
  '/app/provider': typeof AuthenticatedAppProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/join': typeof AuthenticatedJoinRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/app/employee': typeof AuthenticatedAppEmployeeRoute
  '/app/employer': typeof AuthenticatedAppEmployerRoute
  '/app/provider': typeof AuthenticatedAppProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/app/employee': typeof AuthenticatedAppEmployeeRoute
  '/_authenticated/app/employer': typeof AuthenticatedAppEmployerRoute
  '/_authenticated/app/provider': typeof AuthenticatedAppProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/join'
    | '/onboarding'
    | '/app/employee'
    | '/app/employer'
    | '/app/provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/join'
    | '/onboarding'
    | '/app/employee'
    | '/app/employer'
    | '/app/provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/join'
    | '/_authenticated/onboarding'
    | '/_authenticated/app/employee'
    | '/_authenticated/app/employer'
    | '/_authenticated/app/provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/provider': {
      id: '/_authenticated/app/provider'
      path: '/provider'
      fullPath: '/app/provider'
      preLoaderRoute: typeof AuthenticatedAppProviderRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/employer': {
      id: '/_authenticated/app/employer'
      path: '/employer'
      fullPath: '/app/employer'
      preLoaderRoute: typeof AuthenticatedAppEmployerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/employee': {
      id: '/_authenticated/app/employee'
      path: '/employee'
      fullPath: '/app/employee'
      preLoaderRoute: typeof AuthenticatedAppEmployeeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppEmployeeRoute: typeof AuthenticatedAppEmployeeRoute
  AuthenticatedAppEmployerRoute: typeof AuthenticatedAppEmployerRoute
  AuthenticatedAppProviderRoute: typeof AuthenticatedAppProviderRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppEmployeeRoute: AuthenticatedAppEmployeeRoute,
  AuthenticatedAppEmployerRoute: AuthenticatedAppEmployerRoute,
  AuthenticatedAppProviderRoute: AuthenticatedAppProviderRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
